// Package kevy is the first-party Go client for kevy — the pure-Rust
// Redis-compatible engine. It ships two things behind one import:
//
//   - The embedded engine (kevy.go + emb_sub.go, behind the
//     `kevy_embedded` build tag), bound to the C ABI in crates/kevy-ffi:
//     an in-process Store reachable through one Cmd path plus scalar
//     Get/Set and polled pub/sub (contract §5).
//   - The unified Client (client*.go), which routes a single Connect(url)
//     to either the embedded engine (mem:// / file://) or a native RESP
//     TCP server (kevy:// / redis:// / tcp://), exposing every command
//     family with both a blocking and an async face (contract §1–§4).
//
// A protocol error (-ERR …) from the embedded Cmd path is a Reply with
// Kind == KindError, not a Go error: the engine answering "no" is a
// working engine. The typed Client methods, by contrast, map -ERR to a
// *KevyError, because a typed call has exactly one meaning.
package kevy

import (
	"errors"
	"time"
)

// The seam between the two builds of this package.
//
// The remote client is pure Go: it speaks RESP over TCP and needs
// nothing but the standard library, so `go get` gives a working client
// on every platform Go supports. The embedded backend is cgo linked
// against the engine's static library, which is platform-specific and
// tens of megabytes — a Go module ships source, so that library cannot
// travel through the module proxy at all.
//
// So the embedded files carry the `kevy_embedded` build tag and
// register themselves here at init. Without the tag the type is absent,
// the seam is nil, and `mem://` / `file://` fail with a sentence that
// says where to get the other build — rather than with a link error
// about a header nobody has.
//
// Everything outside the tagged files talks to embedded stores through
// these interfaces, which is what lets the standalone module be
// generated by leaving files out instead of by maintaining a parallel
// set of stubs. A stub set would be a second definition of the same
// surface, and the two would drift the first time someone added a
// method to one.

// embStore is the embedded engine handle as the rest of the package
// uses it. `*DB` satisfies it when built with `kevy_embedded`.
// Signatures copied from the methods themselves, not from memory: the
// compiler named every one this got wrong on the first attempt.
type embStore interface {
	Close()
	CmdBytes(args ...[]byte) (Reply, error)
	GetScalar(key []byte) (value []byte, ok bool, err error)
	SetScalar(key, val []byte, ttlMs uint64) error
	subBytes(name []byte, pattern bool) (embSubscription, error)
}

// embSubscription is one embedded pub/sub subscription.
type embSubscription interface {
	Next() (r Reply, ok bool, err error)
	Wait(timeout time.Duration) (r Reply, ok bool, err error)
	Close()
}

// embSubscriber is the multi-channel subscriber the unified Subscriber
// drives when its target is embedded. `*embSub` satisfies it under the
// build tag.
type embSubscriber interface {
	add(names [][]byte, pattern bool) error
	remove(names [][]byte, pattern bool)
	recv(timeout *time.Duration) (Reply, error)
	close()
}

// newEmbSubscriber is installed by the tagged build alongside
// openEmbeddedStore.
var newEmbSubscriber func(db embStore, key string) embSubscriber

// openEmbeddedStore is installed by the tagged build. Nil means this
// binary has no embedded engine compiled in.
var openEmbeddedStore func(t target) (embStore, error)

// errNoEmbedded is what a `mem://` or `file://` URL gets in a build
// without the engine. It names the fix, because "unsupported scheme"
// sends a reader looking for a typo that is not there.
var errNoEmbedded = errors.New(
	"kevy: this build has no embedded engine — mem:// and file:// need " +
		"the cgo backend, built with -tags kevy_embedded against the " +
		"engine's static library (see github.com/goliajp/kevy, " +
		"bindings/go). A kevy:// or redis:// URL needs nothing extra.")
