// CODEGEN: tools/gen_command_specs.py - Redis 8.10.2's COMMAND INFO for the commands
// kevy shares with it. Do not edit; regenerate against the pinned Redis.

use super::command_spec::{Begin, CmdSpec, Find, c, k};

#[rustfmt::skip]
const CLIENT_SUBS: &[CmdSpec] = &[
c("client|caching", 3, &["noscript", "loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &[], &[], &[]),
c("client|pause", -3, &["admin", "noscript", "loading", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous", "@connection"], &[], &[], &[]),
c("client|setinfo", 4, &["noscript", "loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &["request_policy:all_nodes", "response_policy:all_succeeded"], &[], &[]),
c("client|list", -2, &["admin", "noscript", "loading", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous", "@connection"], &["nondeterministic_output"], &[], &[]),
c("client|no-touch", 3, &["noscript", "loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &[], &[], &[]),
c("client|info", 2, &["noscript", "loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &["nondeterministic_output"], &[], &[]),
c("client|help", 2, &["loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &[], &[], &[]),
c("client|id", 2, &["noscript", "loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &[], &[], &[]),
c("client|reply", 3, &["noscript", "loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &[], &[], &[]),
c("client|setname", 3, &["noscript", "loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &["request_policy:all_nodes", "response_policy:all_succeeded"], &[], &[]),
c("client|kill", -3, &["admin", "noscript", "loading", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous", "@connection"], &[], &[], &[]),
c("client|getname", 2, &["noscript", "loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &[], &[], &[]),
c("client|tracking", -3, &["noscript", "loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &[], &[], &[]),
c("client|unblock", -3, &["admin", "noscript", "loading", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous", "@connection"], &[], &[], &[]),
c("client|getredir", 2, &["noscript", "loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &[], &[], &[]),
c("client|no-evict", 3, &["admin", "noscript", "loading", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous", "@connection"], &[], &[], &[]),
c("client|trackinginfo", 2, &["noscript", "loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &[], &[], &[]),
c("client|unpause", 2, &["admin", "noscript", "loading", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous", "@connection"], &[], &[], &[]),
];

#[rustfmt::skip]
const CLUSTER_SUBS: &[CmdSpec] = &[
c("cluster|shards", 2, &["loading", "stale"], 0, 0, 0, &["@slow"], &["nondeterministic_output"], &[], &[]),
c("cluster|delslots", -3, &["admin", "stale", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("cluster|links", 2, &["loading", "stale"], 0, 0, 0, &["@slow"], &["nondeterministic_output"], &[], &[]),
c("cluster|saveconfig", 2, &["admin", "stale", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("cluster|slot-stats", -4, &["loading", "stale"], 0, 0, 0, &["@slow"], &["nondeterministic_output", "request_policy:all_shards"], &[], &[]),
c("cluster|bumpepoch", 2, &["admin", "stale", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &["nondeterministic_output"], &[], &[]),
c("cluster|keyslot", 3, &["loading", "stale"], 0, 0, 0, &["@slow"], &[], &[], &[]),
c("cluster|countkeysinslot", 3, &["stale"], 0, 0, 0, &["@slow"], &[], &[], &[]),
c("cluster|addslotsrange", -4, &["admin", "stale", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("cluster|syncslots", -3, &["admin", "stale", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &["nondeterministic_output"], &[], &[]),
c("cluster|slaves", 3, &["admin", "loading", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &["nondeterministic_output"], &[], &[]),
c("cluster|nodes", 2, &["loading", "stale"], 0, 0, 0, &["@slow"], &["nondeterministic_output"], &[], &[]),
c("cluster|slots", 2, &["loading", "stale"], 0, 0, 0, &["@slow"], &["nondeterministic_output"], &[], &[]),
c("cluster|addslots", -3, &["admin", "stale", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("cluster|count-failure-reports", 3, &["admin", "loading", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &["nondeterministic_output"], &[], &[]),
c("cluster|flushslots", 2, &["admin", "stale", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("cluster|delslotsrange", -4, &["admin", "stale", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("cluster|reset", -2, &["admin", "noscript", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("cluster|setslot", -4, &["admin", "stale", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("cluster|set-config-epoch", 3, &["admin", "stale", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("cluster|help", 2, &["loading", "stale"], 0, 0, 0, &["@slow"], &[], &[], &[]),
c("cluster|info", 2, &["loading", "stale"], 0, 0, 0, &["@slow"], &["nondeterministic_output"], &[], &[]),
c("cluster|myid", 2, &["loading", "stale"], 0, 0, 0, &["@slow"], &[], &[], &[]),
c("cluster|replicas", 3, &["admin", "loading", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &["nondeterministic_output"], &[], &[]),
c("cluster|myshardid", 2, &["loading", "stale"], 0, 0, 0, &["@slow"], &["nondeterministic_output"], &[], &[]),
c("cluster|failover", -2, &["admin", "stale", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("cluster|getkeysinslot", 4, &["stale"], 0, 0, 0, &["@slow"], &["nondeterministic_output"], &[], &[]),
c("cluster|replicate", 3, &["admin", "stale", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("cluster|migration", -4, &["admin", "stale", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("cluster|forget", 3, &["admin", "stale", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("cluster|meet", -4, &["admin", "stale", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
];

#[rustfmt::skip]
const COMMAND_SUBS: &[CmdSpec] = &[
c("command|list", -2, &["loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &["nondeterministic_output_order"], &[], &[]),
c("command|info", -2, &["loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &["nondeterministic_output_order"], &[], &[]),
c("command|help", 2, &["loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &[], &[], &[]),
c("command|count", 2, &["loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &[], &[], &[]),
c("command|getkeysandflags", -3, &["loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &[], &[], &[]),
c("command|docs", -2, &["loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &["nondeterministic_output_order"], &[], &[]),
c("command|getkeys", -3, &["loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &[], &[], &[]),
];

#[rustfmt::skip]
const CONFIG_SUBS: &[CmdSpec] = &[
c("config|get", -3, &["admin", "noscript", "loading", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("config|help", 2, &["loading", "stale"], 0, 0, 0, &["@slow"], &[], &[], &[]),
c("config|resetstat", 2, &["admin", "noscript", "loading", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &["request_policy:all_nodes", "response_policy:all_succeeded"], &[], &[]),
c("config|set", -4, &["admin", "noscript", "loading", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &["request_policy:all_nodes", "response_policy:all_succeeded"], &[], &[]),
c("config|rewrite", 2, &["admin", "noscript", "loading", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &["request_policy:all_nodes", "response_policy:all_succeeded"], &[], &[]),
];

#[rustfmt::skip]
const MEMORY_SUBS: &[CmdSpec] = &[
c("memory|usage", -3, &["readonly"], 2, 2, 1, &["@read", "@slow"], &[], &[k("", &["RO"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
c("memory|help", 2, &["loading", "stale"], 0, 0, 0, &["@slow"], &[], &[], &[]),
c("memory|malloc-stats", 2, &[], 0, 0, 0, &["@slow"], &["nondeterministic_output", "request_policy:all_shards", "response_policy:special"], &[], &[]),
c("memory|purge", 2, &[], 0, 0, 0, &["@slow"], &["request_policy:all_shards", "response_policy:all_succeeded"], &[], &[]),
c("memory|stats", 2, &[], 0, 0, 0, &["@slow"], &["nondeterministic_output", "request_policy:all_shards", "response_policy:special"], &[], &[]),
c("memory|doctor", 2, &[], 0, 0, 0, &["@slow"], &["nondeterministic_output", "request_policy:all_shards", "response_policy:special"], &[], &[]),
];

#[rustfmt::skip]
const PUBSUB_SUBS: &[CmdSpec] = &[
c("pubsub|channels", -2, &["pubsub", "loading", "stale"], 0, 0, 0, &["@pubsub", "@slow"], &[], &[], &[]),
c("pubsub|help", 2, &["loading", "stale"], 0, 0, 0, &["@slow"], &[], &[], &[]),
c("pubsub|numpat", 2, &["pubsub", "loading", "stale"], 0, 0, 0, &["@pubsub", "@slow"], &[], &[], &[]),
c("pubsub|shardchannels", -2, &["pubsub", "loading", "stale"], 0, 0, 0, &["@pubsub", "@slow"], &[], &[], &[]),
c("pubsub|shardnumsub", -2, &["pubsub", "loading", "stale"], 0, 0, 0, &["@pubsub", "@slow"], &[], &[], &[]),
c("pubsub|numsub", -2, &["pubsub", "loading", "stale"], 0, 0, 0, &["@pubsub", "@slow"], &[], &[], &[]),
];

#[rustfmt::skip]
const SCRIPT_SUBS: &[CmdSpec] = &[
c("script|debug", 3, &["noscript"], 0, 0, 0, &["@slow", "@scripting"], &[], &[], &[]),
c("script|exists", -3, &["noscript"], 0, 0, 0, &["@slow", "@scripting"], &["request_policy:all_shards", "response_policy:agg_logical_and"], &[], &[]),
c("script|help", 2, &["loading", "stale"], 0, 0, 0, &["@slow", "@scripting"], &[], &[], &[]),
c("script|load", 3, &["noscript", "stale"], 0, 0, 0, &["@slow", "@scripting"], &["request_policy:all_nodes", "response_policy:all_succeeded"], &[], &[]),
c("script|kill", 2, &["noscript", "allow_busy"], 0, 0, 0, &["@slow", "@scripting"], &["request_policy:all_shards", "response_policy:one_succeeded"], &[], &[]),
c("script|flush", -2, &["noscript"], 0, 0, 0, &["@slow", "@scripting"], &["request_policy:all_nodes", "response_policy:all_succeeded"], &[], &[]),
];

#[rustfmt::skip]
const SLOWLOG_SUBS: &[CmdSpec] = &[
c("slowlog|reset", 2, &["admin", "loading", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &["request_policy:all_nodes", "response_policy:all_succeeded"], &[], &[]),
c("slowlog|len", 2, &["admin", "loading", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &["request_policy:all_nodes", "response_policy:agg_sum", "nondeterministic_output"], &[], &[]),
c("slowlog|help", 2, &["loading", "stale"], 0, 0, 0, &["@slow"], &[], &[], &[]),
c("slowlog|get", -2, &["admin", "loading", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &["request_policy:all_nodes", "nondeterministic_output"], &[], &[]),
];

#[rustfmt::skip]
const XGROUP_SUBS: &[CmdSpec] = &[
c("xgroup|setid", -5, &["write"], 2, 2, 1, &["@write", "@stream", "@slow"], &[], &[k("", &["RW", "update"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
c("xgroup|help", 2, &["loading", "stale"], 0, 0, 0, &["@stream", "@slow"], &[], &[], &[]),
c("xgroup|delconsumer", 5, &["write"], 2, 2, 1, &["@write", "@stream", "@slow"], &[], &[k("", &["RW", "delete"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
c("xgroup|create", -5, &["write", "denyoom"], 2, 2, 1, &["@write", "@stream", "@slow"], &[], &[k("", &["RW", "insert"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
c("xgroup|destroy", 4, &["write"], 2, 2, 1, &["@write", "@stream", "@slow"], &[], &[k("", &["RW", "delete"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
c("xgroup|createconsumer", 5, &["write", "denyoom"], 2, 2, 1, &["@write", "@stream", "@slow"], &[], &[k("", &["RW", "insert"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
];

#[rustfmt::skip]
const XINFO_SUBS: &[CmdSpec] = &[
c("xinfo|help", 2, &["loading", "stale"], 0, 0, 0, &["@stream", "@slow"], &[], &[], &[]),
c("xinfo|groups", 3, &["readonly"], 2, 2, 1, &["@read", "@stream", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
c("xinfo|consumers", 4, &["readonly"], 2, 2, 1, &["@read", "@stream", "@slow"], &["nondeterministic_output"], &[k("", &["RO", "access"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
c("xinfo|stream", -3, &["readonly"], 2, 2, 1, &["@read", "@stream", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
];

/// Every shared command's row, sorted by name.
#[rustfmt::skip]
pub(super) static SPECS: &[CmdSpec] = &[
c("append", 3, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@string", "@fast"], &[], &[k("", &["RW", "insert"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("bgrewriteaof", 1, &["admin", "noscript", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("bgsave", -1, &["admin", "noscript", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("bitcount", -2, &["readonly"], 1, 1, 1, &["@read", "@bitmap", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("bitfield", -2, &["write", "denyoom"], 1, 1, 1, &["@write", "@bitmap", "@slow"], &[], &[k("This command allows both access and modification of the key", &["RW", "access", "update", "variable_flags"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("bitfield_ro", -2, &["readonly", "fast"], 1, 1, 1, &["@read", "@bitmap", "@fast"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("bitop", -4, &["write", "denyoom"], 2, -1, 1, &["@write", "@bitmap", "@slow"], &[], &[k("", &["OW", "update"], Begin::Index(2), Find::Range(0, 1, 0)), k("", &["RO", "access"], Begin::Index(3), Find::Range(-1, 1, 0))], &[]),
c("bitpos", -3, &["readonly"], 1, 1, 1, &["@read", "@bitmap", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("blmove", 6, &["write", "denyoom", "blocking"], 1, 2, 1, &["@write", "@list", "@slow", "@blocking"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::Range(0, 1, 0)), k("", &["RW", "insert"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
c("blmpop", -5, &["write", "blocking", "movablekeys"], 0, 0, 0, &["@write", "@list", "@slow", "@blocking"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(2), Find::KeyNum(0, 1, 1))], &[]),
c("blpop", -3, &["write", "blocking"], 1, -2, 1, &["@write", "@list", "@slow", "@blocking"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::Range(-2, 1, 0))], &[]),
c("brpop", -3, &["write", "blocking"], 1, -2, 1, &["@write", "@list", "@slow", "@blocking"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::Range(-2, 1, 0))], &[]),
c("brpoplpush", 4, &["write", "denyoom", "blocking"], 1, 2, 1, &["@write", "@list", "@slow", "@blocking"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::Range(0, 1, 0)), k("", &["RW", "insert"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
c("bzmpop", -5, &["write", "blocking", "movablekeys"], 0, 0, 0, &["@write", "@sortedset", "@slow", "@blocking"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(2), Find::KeyNum(0, 1, 1))], &[]),
c("bzpopmax", -3, &["write", "blocking", "fast"], 1, -2, 1, &["@write", "@sortedset", "@fast", "@blocking"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::Range(-2, 1, 0))], &[]),
c("bzpopmin", -3, &["write", "blocking", "fast"], 1, -2, 1, &["@write", "@sortedset", "@fast", "@blocking"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::Range(-2, 1, 0))], &[]),
c("client", -2, &[], 0, 0, 0, &["@slow"], &[], &[], CLIENT_SUBS),
c("cluster", -2, &[], 0, 0, 0, &["@slow"], &[], &[], CLUSTER_SUBS),
c("command", -1, &["loading", "stale"], 0, 0, 0, &["@slow", "@connection"], &["nondeterministic_output_order"], &[], COMMAND_SUBS),
c("config", -2, &[], 0, 0, 0, &["@slow"], &[], &[], CONFIG_SUBS),
c("copy", -3, &["write", "denyoom"], 1, 2, 1, &["@keyspace", "@write", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0)), k("", &["OW", "update"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
c("dbsize", 1, &["readonly", "fast"], 0, 0, 0, &["@keyspace", "@read", "@fast"], &["request_policy:all_shards", "response_policy:agg_sum"], &[], &[]),
c("debug", -2, &["admin", "noscript", "loading", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("decr", 2, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@string", "@fast"], &[], &[k("", &["RW", "access", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("decrby", 3, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@string", "@fast"], &[], &[k("", &["RW", "access", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("del", -2, &["write"], 1, -1, 1, &["@keyspace", "@write", "@slow"], &["request_policy:multi_shard", "response_policy:agg_sum"], &[k("", &["RM", "delete"], Begin::Index(1), Find::Range(-1, 1, 0))], &[]),
c("digest", 2, &["readonly", "fast"], 1, 1, 1, &["@read", "@string", "@fast"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("discard", 1, &["noscript", "loading", "stale", "fast", "allow_busy"], 0, 0, 0, &["@fast", "@transaction"], &[], &[], &[]),
c("echo", 2, &["loading", "stale", "fast"], 0, 0, 0, &["@fast", "@connection"], &[], &[], &[]),
c("eval", -3, &["noscript", "stale", "skip_monitor", "no_mandatory_keys", "movablekeys", "script_runner"], 0, 0, 0, &["@slow", "@scripting"], &[], &[k("We cannot tell how the keys will be used so we assume the worst, RW and UPDATE", &["RW", "access", "update"], Begin::Index(2), Find::KeyNum(0, 1, 1))], &[]),
c("evalsha", -3, &["noscript", "stale", "skip_monitor", "no_mandatory_keys", "movablekeys", "script_runner"], 0, 0, 0, &["@slow", "@scripting"], &[], &[k("", &["RW", "access", "update"], Begin::Index(2), Find::KeyNum(0, 1, 1))], &[]),
c("exec", 1, &["noscript", "loading", "stale", "skip_slowlog"], 0, 0, 0, &["@slow", "@transaction"], &[], &[], &[]),
c("exists", -2, &["readonly", "fast"], 1, -1, 1, &["@keyspace", "@read", "@fast"], &["request_policy:multi_shard", "response_policy:agg_sum"], &[k("", &["RO"], Begin::Index(1), Find::Range(-1, 1, 0))], &[]),
c("expire", -3, &["write", "fast"], 1, 1, 1, &["@keyspace", "@write", "@fast"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("expireat", -3, &["write", "fast"], 1, 1, 1, &["@keyspace", "@write", "@fast"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("expiretime", 2, &["readonly", "fast"], 1, 1, 1, &["@keyspace", "@read", "@fast"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("failover", -1, &["admin", "noscript", "stale"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("flushall", -1, &["write"], 0, 0, 0, &["@keyspace", "@write", "@slow", "@dangerous"], &["request_policy:all_shards", "response_policy:all_succeeded"], &[], &[]),
c("flushdb", -1, &["write"], 0, 0, 0, &["@keyspace", "@write", "@slow", "@dangerous"], &["request_policy:all_shards", "response_policy:all_succeeded"], &[], &[]),
c("geoadd", -5, &["write", "denyoom"], 1, 1, 1, &["@write", "@geo", "@slow"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("geodist", -4, &["readonly"], 1, 1, 1, &["@read", "@geo", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("geohash", -2, &["readonly"], 1, 1, 1, &["@read", "@geo", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("geopos", -2, &["readonly"], 1, 1, 1, &["@read", "@geo", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("georadius", -6, &["write", "denyoom", "movablekeys"], 1, 1, 1, &["@write", "@geo", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0)), k("Incomplete because duplicate STORE options use last-wins; fall back to georadiusGetKeys", &["OW", "update", "incomplete"], Begin::Keyword("STORE", 6), Find::Range(0, 1, 0)), k("Incomplete because duplicate STOREDIST options use last-wins; fall back to georadiusGetKeys", &["OW", "update", "incomplete"], Begin::Keyword("STOREDIST", 6), Find::Range(0, 1, 0))], &[]),
c("georadiusbymember", -5, &["write", "denyoom", "movablekeys"], 1, 1, 1, &["@write", "@geo", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0)), k("Incomplete because duplicate STORE options use last-wins; fall back to georadiusGetKeys", &["OW", "update", "incomplete"], Begin::Keyword("STORE", 5), Find::Range(0, 1, 0)), k("Incomplete because duplicate STOREDIST options use last-wins; fall back to georadiusGetKeys", &["OW", "update", "incomplete"], Begin::Keyword("STOREDIST", 5), Find::Range(0, 1, 0))], &[]),
c("geosearch", -7, &["readonly"], 1, 1, 1, &["@read", "@geo", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("geosearchstore", -8, &["write", "denyoom"], 1, 2, 1, &["@write", "@geo", "@slow"], &[], &[k("", &["OW", "update"], Begin::Index(1), Find::Range(0, 1, 0)), k("", &["RO", "access"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
c("get", 2, &["readonly", "fast"], 1, 1, 1, &["@read", "@string", "@fast"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("getbit", 3, &["readonly", "fast"], 1, 1, 1, &["@read", "@bitmap", "@fast"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("getdel", 2, &["write", "fast"], 1, 1, 1, &["@write", "@string", "@fast"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("getex", -2, &["write", "fast"], 1, 1, 1, &["@write", "@string", "@fast"], &[], &[k("RW and UPDATE because it changes the TTL", &["RW", "access", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("getrange", 4, &["readonly"], 1, 1, 1, &["@read", "@string", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("getset", 3, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@string", "@fast"], &[], &[k("", &["RW", "access", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hdel", -3, &["write", "fast"], 1, 1, 1, &["@write", "@hash", "@fast"], &[], &[k("", &["RW", "delete"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hello", -1, &["noscript", "loading", "stale", "fast", "no_auth", "allow_busy"], 0, 0, 0, &["@fast", "@connection"], &[], &[], &[]),
c("hexists", 3, &["readonly", "fast"], 1, 1, 1, &["@read", "@hash", "@fast"], &[], &[k("", &["RO"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hexpire", -6, &["write", "fast"], 1, 1, 1, &["@write", "@hash", "@fast"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hexpireat", -6, &["write", "fast"], 1, 1, 1, &["@write", "@hash", "@fast"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hexpiretime", -5, &["readonly", "fast"], 1, 1, 1, &["@read", "@hash", "@fast"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hget", 3, &["readonly", "fast"], 1, 1, 1, &["@read", "@hash", "@fast"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hgetall", 2, &["readonly"], 1, 1, 1, &["@read", "@hash", "@slow"], &["nondeterministic_output_order"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hincrby", 4, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@hash", "@fast"], &[], &[k("", &["RW", "access", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hincrbyfloat", 4, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@hash", "@fast"], &[], &[k("", &["RW", "access", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hkeys", 2, &["readonly"], 1, 1, 1, &["@read", "@hash", "@slow"], &["nondeterministic_output_order"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hlen", 2, &["readonly", "fast"], 1, 1, 1, &["@read", "@hash", "@fast"], &[], &[k("", &["RO"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hmget", -3, &["readonly", "fast"], 1, 1, 1, &["@read", "@hash", "@fast"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hmset", -4, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@hash", "@fast"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hpersist", -5, &["write", "fast"], 1, 1, 1, &["@write", "@hash", "@fast"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hpexpire", -6, &["write", "fast"], 1, 1, 1, &["@write", "@hash", "@fast"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hpexpireat", -6, &["write", "fast"], 1, 1, 1, &["@write", "@hash", "@fast"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hpexpiretime", -5, &["readonly", "fast"], 1, 1, 1, &["@read", "@hash", "@fast"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hpttl", -5, &["readonly", "fast"], 1, 1, 1, &["@read", "@hash", "@fast"], &["nondeterministic_output"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hrandfield", -2, &["readonly"], 1, 1, 1, &["@read", "@hash", "@slow"], &["nondeterministic_output"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hscan", -3, &["readonly"], 1, 1, 1, &["@read", "@hash", "@slow"], &["nondeterministic_output"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hset", -4, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@hash", "@fast"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hsetnx", 4, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@hash", "@fast"], &[], &[k("", &["RW", "insert"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hstrlen", 3, &["readonly", "fast"], 1, 1, 1, &["@read", "@hash", "@fast"], &[], &[k("", &["RO"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("httl", -5, &["readonly", "fast"], 1, 1, 1, &["@read", "@hash", "@fast"], &["nondeterministic_output"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("hvals", 2, &["readonly"], 1, 1, 1, &["@read", "@hash", "@slow"], &["nondeterministic_output_order"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("incr", 2, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@string", "@fast"], &[], &[k("", &["RW", "access", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("incrby", 3, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@string", "@fast"], &[], &[k("", &["RW", "access", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("incrbyfloat", 3, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@string", "@fast"], &[], &[k("", &["RW", "access", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("info", -1, &["loading", "stale"], 0, 0, 0, &["@slow", "@dangerous"], &["nondeterministic_output", "request_policy:all_shards", "response_policy:special"], &[], &[]),
c("keys", 2, &["readonly"], 0, 0, 0, &["@keyspace", "@read", "@slow", "@dangerous"], &["request_policy:all_shards", "nondeterministic_output_order"], &[], &[]),
c("lcs", -3, &["readonly"], 1, 2, 1, &["@read", "@string", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(1, 1, 0))], &[]),
c("lindex", 3, &["readonly"], 1, 1, 1, &["@read", "@list", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("linsert", 5, &["write", "denyoom"], 1, 1, 1, &["@write", "@list", "@slow"], &[], &[k("", &["RW", "insert"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("llen", 2, &["readonly", "fast"], 1, 1, 1, &["@read", "@list", "@fast"], &[], &[k("", &["RO"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("lmove", 5, &["write", "denyoom"], 1, 2, 1, &["@write", "@list", "@slow"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::Range(0, 1, 0)), k("", &["RW", "insert"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
c("lmpop", -4, &["write", "movablekeys"], 0, 0, 0, &["@write", "@list", "@slow"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::KeyNum(0, 1, 1))], &[]),
c("lpop", -2, &["write", "fast"], 1, 1, 1, &["@write", "@list", "@fast"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("lpos", -3, &["readonly"], 1, 1, 1, &["@read", "@list", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("lpush", -3, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@list", "@fast"], &[], &[k("", &["RW", "insert"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("lpushx", -3, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@list", "@fast"], &[], &[k("", &["RW", "insert"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("lrange", 4, &["readonly"], 1, 1, 1, &["@read", "@list", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("lrem", 4, &["write"], 1, 1, 1, &["@write", "@list", "@slow"], &[], &[k("", &["RW", "delete"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("lset", 4, &["write", "denyoom"], 1, 1, 1, &["@write", "@list", "@slow"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("ltrim", 4, &["write"], 1, 1, 1, &["@write", "@list", "@slow"], &[], &[k("", &["RW", "delete"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("memory", -2, &[], 0, 0, 0, &["@slow"], &[], &[], MEMORY_SUBS),
c("mget", -2, &["readonly", "fast"], 1, -1, 1, &["@read", "@string", "@fast"], &["request_policy:multi_shard"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(-1, 1, 0))], &[]),
c("mset", -3, &["write", "denyoom"], 1, -1, 2, &["@write", "@string", "@slow"], &["request_policy:multi_shard", "response_policy:all_succeeded"], &[k("", &["OW", "update"], Begin::Index(1), Find::Range(-1, 2, 0))], &[]),
c("msetnx", -3, &["write", "denyoom"], 1, -1, 2, &["@write", "@string", "@slow"], &[], &[k("", &["OW", "insert"], Begin::Index(1), Find::Range(-1, 2, 0))], &[]),
c("multi", 1, &["noscript", "loading", "stale", "fast", "allow_busy"], 0, 0, 0, &["@fast", "@transaction"], &[], &[], &[]),
c("persist", 2, &["write", "fast"], 1, 1, 1, &["@keyspace", "@write", "@fast"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("pexpire", -3, &["write", "fast"], 1, 1, 1, &["@keyspace", "@write", "@fast"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("pexpireat", -3, &["write", "fast"], 1, 1, 1, &["@keyspace", "@write", "@fast"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("pexpiretime", 2, &["readonly", "fast"], 1, 1, 1, &["@keyspace", "@read", "@fast"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("pfadd", -2, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@hyperloglog", "@fast"], &[], &[k("", &["RW", "insert"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("pfcount", -2, &["readonly"], 1, -1, 1, &["@read", "@hyperloglog", "@slow"], &[], &[k("RW because it may change the internal representation of the key, and propagate to replicas", &["RW", "access"], Begin::Index(1), Find::Range(-1, 1, 0))], &[]),
c("pfmerge", -2, &["write", "denyoom"], 1, -1, 1, &["@write", "@hyperloglog", "@slow"], &[], &[k("", &["RW", "access", "insert"], Begin::Index(1), Find::Range(0, 1, 0)), k("", &["RO", "access"], Begin::Index(2), Find::Range(-1, 1, 0))], &[]),
c("ping", -1, &["fast"], 0, 0, 0, &["@fast", "@connection"], &["request_policy:all_shards", "response_policy:all_succeeded"], &[], &[]),
c("psetex", 4, &["write", "denyoom"], 1, 1, 1, &["@write", "@string", "@slow"], &[], &[k("", &["OW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("psubscribe", -2, &["denyoom", "pubsub", "noscript", "loading", "stale"], 0, 0, 0, &["@pubsub", "@slow"], &[], &[], &[]),
c("pttl", 2, &["readonly", "fast"], 1, 1, 1, &["@keyspace", "@read", "@fast"], &["nondeterministic_output"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("publish", 3, &["pubsub", "loading", "stale", "fast"], 0, 0, 0, &["@pubsub", "@fast"], &[], &[], &[]),
c("pubsub", -2, &[], 0, 0, 0, &["@slow"], &[], &[], PUBSUB_SUBS),
c("punsubscribe", -1, &["pubsub", "noscript", "loading", "stale"], 0, 0, 0, &["@pubsub", "@slow"], &[], &[], &[]),
c("quit", -1, &["noscript", "loading", "stale", "fast", "no_auth", "allow_busy"], 0, 0, 0, &["@fast", "@connection"], &[], &[], &[]),
c("randomkey", 1, &["readonly"], 0, 0, 0, &["@keyspace", "@read", "@slow"], &["request_policy:all_shards", "response_policy:special", "nondeterministic_output"], &[], &[]),
c("rename", 3, &["write"], 1, 2, 1, &["@keyspace", "@write", "@slow"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::Range(0, 1, 0)), k("", &["OW", "update"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
c("renamenx", 3, &["write", "fast"], 1, 2, 1, &["@keyspace", "@write", "@fast"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::Range(0, 1, 0)), k("", &["OW", "insert"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
c("replicaof", 3, &["admin", "noscript", "stale", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("reset", 1, &["noscript", "loading", "stale", "fast", "no_auth", "allow_busy"], 0, 0, 0, &["@fast", "@connection"], &[], &[], &[]),
c("role", 1, &["noscript", "loading", "stale", "fast"], 0, 0, 0, &["@admin", "@fast", "@dangerous"], &[], &[], &[]),
c("rpop", -2, &["write", "fast"], 1, 1, 1, &["@write", "@list", "@fast"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("rpoplpush", 3, &["write", "denyoom"], 1, 2, 1, &["@write", "@list", "@slow"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::Range(0, 1, 0)), k("", &["RW", "insert"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
c("rpush", -3, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@list", "@fast"], &[], &[k("", &["RW", "insert"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("rpushx", -3, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@list", "@fast"], &[], &[k("", &["RW", "insert"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("sadd", -3, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@set", "@fast"], &[], &[k("", &["RW", "insert"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("save", 1, &["admin", "noscript", "no_async_loading", "no_multi"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("scan", -2, &["readonly"], 0, 0, 0, &["@keyspace", "@read", "@slow"], &["nondeterministic_output", "request_policy:special", "response_policy:special"], &[], &[]),
c("scard", 2, &["readonly", "fast"], 1, 1, 1, &["@read", "@set", "@fast"], &[], &[k("", &["RO"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("script", -2, &[], 0, 0, 0, &["@slow"], &[], &[], SCRIPT_SUBS),
c("sdiff", -2, &["readonly"], 1, -1, 1, &["@read", "@set", "@slow"], &["nondeterministic_output_order"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(-1, 1, 0))], &[]),
c("sdiffstore", -3, &["write", "denyoom"], 1, -1, 1, &["@write", "@set", "@slow"], &[], &[k("", &["OW", "update"], Begin::Index(1), Find::Range(0, 1, 0)), k("", &["RO", "access"], Begin::Index(2), Find::Range(-1, 1, 0))], &[]),
c("select", 2, &["loading", "stale", "fast"], 0, 0, 0, &["@fast", "@connection"], &[], &[], &[]),
c("set", -3, &["write", "denyoom"], 1, 1, 1, &["@write", "@string", "@slow"], &[], &[k("RW and ACCESS due to the optional `GET` argument", &["RW", "access", "update", "variable_flags"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("setbit", 4, &["write", "denyoom"], 1, 1, 1, &["@write", "@bitmap", "@slow"], &[], &[k("", &["RW", "access", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("setex", 4, &["write", "denyoom"], 1, 1, 1, &["@write", "@string", "@slow"], &[], &[k("", &["OW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("setnx", 3, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@string", "@fast"], &[], &[k("", &["OW", "insert"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("setrange", 4, &["write", "denyoom"], 1, 1, 1, &["@write", "@string", "@slow"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("shutdown", -1, &["admin", "noscript", "loading", "stale", "no_multi", "allow_busy"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("sinter", -2, &["readonly"], 1, -1, 1, &["@read", "@set", "@slow"], &["nondeterministic_output_order"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(-1, 1, 0))], &[]),
c("sintercard", -3, &["readonly", "movablekeys"], 0, 0, 0, &["@read", "@set", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::KeyNum(0, 1, 1))], &[]),
c("sinterstore", -3, &["write", "denyoom"], 1, -1, 1, &["@write", "@set", "@slow"], &[], &[k("", &["OW", "update"], Begin::Index(1), Find::Range(0, 1, 0)), k("", &["RO", "access"], Begin::Index(2), Find::Range(-1, 1, 0))], &[]),
c("sismember", 3, &["readonly", "fast"], 1, 1, 1, &["@read", "@set", "@fast"], &[], &[k("", &["RO"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("slaveof", 3, &["admin", "noscript", "stale", "no_async_loading"], 0, 0, 0, &["@admin", "@slow", "@dangerous"], &[], &[], &[]),
c("slowlog", -2, &[], 0, 0, 0, &["@slow"], &[], &[], SLOWLOG_SUBS),
c("smembers", 2, &["readonly"], 1, 1, 1, &["@read", "@set", "@slow"], &["nondeterministic_output_order"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("smismember", -3, &["readonly", "fast"], 1, 1, 1, &["@read", "@set", "@fast"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("smove", 4, &["write", "fast"], 1, 2, 1, &["@write", "@set", "@fast"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::Range(0, 1, 0)), k("", &["RW", "insert"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
c("sort", -2, &["write", "denyoom", "movablekeys"], 1, 1, 1, &["@write", "@set", "@sortedset", "@list", "@slow", "@dangerous"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0)), k("For the optional BY/GET keyword. It is marked 'unknown' because the key names derive from the content of the key we sort", &["RO", "access"], Begin::Unknown, Find::Unknown), k("For the optional STORE keyword. It is marked 'unknown' because the keyword can appear anywhere in the argument array", &["OW", "update"], Begin::Unknown, Find::Unknown)], &[]),
c("sort_ro", -2, &["readonly", "movablekeys"], 1, 1, 1, &["@read", "@set", "@sortedset", "@list", "@slow", "@dangerous"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0)), k("For the optional BY/GET keyword. It is marked 'unknown' because the key names derive from the content of the key we sort", &["RO", "access"], Begin::Unknown, Find::Unknown)], &[]),
c("spop", -2, &["write", "fast"], 1, 1, 1, &["@write", "@set", "@fast"], &["nondeterministic_output"], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("srandmember", -2, &["readonly"], 1, 1, 1, &["@read", "@set", "@slow"], &["nondeterministic_output"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("srem", -3, &["write", "fast"], 1, 1, 1, &["@write", "@set", "@fast"], &[], &[k("", &["RW", "delete"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("sscan", -3, &["readonly"], 1, 1, 1, &["@read", "@set", "@slow"], &["nondeterministic_output"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("strlen", 2, &["readonly", "fast"], 1, 1, 1, &["@read", "@string", "@fast"], &[], &[k("", &["RO"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("subscribe", -2, &["denyoom", "pubsub", "noscript", "loading", "stale"], 0, 0, 0, &["@pubsub", "@slow"], &[], &[], &[]),
c("substr", 4, &["readonly"], 1, 1, 1, &["@read", "@string", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("sunion", -2, &["readonly"], 1, -1, 1, &["@read", "@set", "@slow"], &["nondeterministic_output_order"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(-1, 1, 0))], &[]),
c("sunionstore", -3, &["write", "denyoom"], 1, -1, 1, &["@write", "@set", "@slow"], &[], &[k("", &["OW", "update"], Begin::Index(1), Find::Range(0, 1, 0)), k("", &["RO", "access"], Begin::Index(2), Find::Range(-1, 1, 0))], &[]),
c("time", 1, &["loading", "stale", "fast"], 0, 0, 0, &["@fast"], &["nondeterministic_output"], &[], &[]),
c("touch", -2, &["readonly", "fast"], 1, -1, 1, &["@keyspace", "@read", "@fast"], &["request_policy:multi_shard", "response_policy:agg_sum"], &[k("", &["RO"], Begin::Index(1), Find::Range(-1, 1, 0))], &[]),
c("ttl", 2, &["readonly", "fast"], 1, 1, 1, &["@keyspace", "@read", "@fast"], &["nondeterministic_output"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("type", 2, &["readonly", "fast"], 1, 1, 1, &["@keyspace", "@read", "@fast"], &[], &[k("", &["RO"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("unlink", -2, &["write", "fast"], 1, -1, 1, &["@keyspace", "@write", "@fast"], &["request_policy:multi_shard", "response_policy:agg_sum"], &[k("", &["RM", "delete"], Begin::Index(1), Find::Range(-1, 1, 0))], &[]),
c("unsubscribe", -1, &["pubsub", "noscript", "loading", "stale"], 0, 0, 0, &["@pubsub", "@slow"], &[], &[], &[]),
c("unwatch", 1, &["noscript", "loading", "stale", "fast", "allow_busy"], 0, 0, 0, &["@fast", "@transaction"], &[], &[], &[]),
c("wait", 3, &["blocking"], 0, 0, 0, &["@slow", "@blocking", "@connection"], &["request_policy:all_shards", "response_policy:agg_min"], &[], &[]),
c("watch", -2, &["noscript", "loading", "stale", "fast", "allow_busy"], 1, -1, 1, &["@fast", "@transaction"], &[], &[k("", &["RO"], Begin::Index(1), Find::Range(-1, 1, 0))], &[]),
c("xack", -4, &["write", "fast"], 1, 1, 1, &["@write", "@stream", "@fast"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("xadd", -5, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@stream", "@fast"], &["nondeterministic_output"], &[k("UPDATE instead of INSERT because of the optional trimming feature", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("xautoclaim", -6, &["write", "fast"], 1, 1, 1, &["@write", "@stream", "@fast"], &["nondeterministic_output"], &[k("", &["RW", "delete"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("xclaim", -6, &["write", "fast"], 1, 1, 1, &["@write", "@stream", "@fast"], &["nondeterministic_output"], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("xdel", -3, &["write", "fast"], 1, 1, 1, &["@write", "@stream", "@fast"], &[], &[k("", &["RW", "delete"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("xgroup", -2, &[], 0, 0, 0, &["@slow"], &[], &[], XGROUP_SUBS),
c("xinfo", -2, &[], 0, 0, 0, &["@slow"], &[], &[], XINFO_SUBS),
c("xlen", 2, &["readonly", "fast"], 1, 1, 1, &["@read", "@stream", "@fast"], &[], &[k("", &["RO"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("xpending", -3, &["readonly"], 1, 1, 1, &["@read", "@stream", "@slow"], &["nondeterministic_output"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("xrange", -4, &["readonly"], 1, 1, 1, &["@read", "@stream", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("xread", -4, &["readonly", "blocking", "movablekeys"], 0, 0, 0, &["@read", "@stream", "@slow", "@blocking"], &[], &[k("Incomplete because a stream key named STREAMS (or options before it) can shift the STREAMS keyword; fall back to xreadGetKeys", &["RO", "access", "incomplete"], Begin::Keyword("STREAMS", 1), Find::Range(-1, 1, 2))], &[]),
c("xreadgroup", -7, &["write", "blocking", "movablekeys"], 0, 0, 0, &["@write", "@stream", "@slow", "@blocking"], &[], &[k("Incomplete because a consumer/group named STREAMS (or options before GROUP) can shift the STREAMS keyword; fall back to xreadGetKeys", &["RO", "access", "incomplete"], Begin::Keyword("STREAMS", 4), Find::Range(-1, 1, 2))], &[]),
c("xrevrange", -4, &["readonly"], 1, 1, 1, &["@read", "@stream", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("xsetid", -3, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@stream", "@fast"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("xtrim", -4, &["write"], 1, 1, 1, &["@write", "@stream", "@slow"], &["nondeterministic_output"], &[k("", &["RW", "delete"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zadd", -4, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@sortedset", "@fast"], &[], &[k("", &["RW", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zcard", 2, &["readonly", "fast"], 1, 1, 1, &["@read", "@sortedset", "@fast"], &[], &[k("", &["RO"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zcount", 4, &["readonly", "fast"], 1, 1, 1, &["@read", "@sortedset", "@fast"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zdiff", -3, &["readonly", "movablekeys"], 0, 0, 0, &["@read", "@sortedset", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::KeyNum(0, 1, 1))], &[]),
c("zdiffstore", -4, &["write", "denyoom", "movablekeys"], 1, 1, 1, &["@write", "@sortedset", "@slow"], &[], &[k("", &["OW", "update"], Begin::Index(1), Find::Range(0, 1, 0)), k("", &["RO", "access"], Begin::Index(2), Find::KeyNum(0, 1, 1))], &[]),
c("zincrby", 4, &["write", "denyoom", "fast"], 1, 1, 1, &["@write", "@sortedset", "@fast"], &[], &[k("", &["RW", "access", "update"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zinter", -3, &["readonly", "movablekeys"], 0, 0, 0, &["@read", "@sortedset", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::KeyNum(0, 1, 1))], &[]),
c("zintercard", -3, &["readonly", "movablekeys"], 0, 0, 0, &["@read", "@sortedset", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::KeyNum(0, 1, 1))], &[]),
c("zinterstore", -4, &["write", "denyoom", "movablekeys"], 1, 1, 1, &["@write", "@sortedset", "@slow"], &[], &[k("", &["OW", "update"], Begin::Index(1), Find::Range(0, 1, 0)), k("", &["RO", "access"], Begin::Index(2), Find::KeyNum(0, 1, 1))], &[]),
c("zlexcount", 4, &["readonly", "fast"], 1, 1, 1, &["@read", "@sortedset", "@fast"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zmpop", -4, &["write", "movablekeys"], 0, 0, 0, &["@write", "@sortedset", "@slow"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::KeyNum(0, 1, 1))], &[]),
c("zmscore", -3, &["readonly", "fast"], 1, 1, 1, &["@read", "@sortedset", "@fast"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zpopmax", -2, &["write", "fast"], 1, 1, 1, &["@write", "@sortedset", "@fast"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zpopmin", -2, &["write", "fast"], 1, 1, 1, &["@write", "@sortedset", "@fast"], &[], &[k("", &["RW", "access", "delete"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zrandmember", -2, &["readonly"], 1, 1, 1, &["@read", "@sortedset", "@slow"], &["nondeterministic_output"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zrange", -4, &["readonly"], 1, 1, 1, &["@read", "@sortedset", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zrangebylex", -4, &["readonly"], 1, 1, 1, &["@read", "@sortedset", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zrangebyscore", -4, &["readonly"], 1, 1, 1, &["@read", "@sortedset", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zrangestore", -5, &["write", "denyoom"], 1, 2, 1, &["@write", "@sortedset", "@slow"], &[], &[k("", &["OW", "update"], Begin::Index(1), Find::Range(0, 1, 0)), k("", &["RO", "access"], Begin::Index(2), Find::Range(0, 1, 0))], &[]),
c("zrank", -3, &["readonly", "fast"], 1, 1, 1, &["@read", "@sortedset", "@fast"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zrem", -3, &["write", "fast"], 1, 1, 1, &["@write", "@sortedset", "@fast"], &[], &[k("", &["RW", "delete"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zremrangebylex", 4, &["write"], 1, 1, 1, &["@write", "@sortedset", "@slow"], &[], &[k("", &["RW", "delete"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zremrangebyrank", 4, &["write"], 1, 1, 1, &["@write", "@sortedset", "@slow"], &[], &[k("", &["RW", "delete"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zremrangebyscore", 4, &["write"], 1, 1, 1, &["@write", "@sortedset", "@slow"], &[], &[k("", &["RW", "delete"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zrevrange", -4, &["readonly"], 1, 1, 1, &["@read", "@sortedset", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zrevrangebylex", -4, &["readonly"], 1, 1, 1, &["@read", "@sortedset", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zrevrangebyscore", -4, &["readonly"], 1, 1, 1, &["@read", "@sortedset", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zrevrank", -3, &["readonly", "fast"], 1, 1, 1, &["@read", "@sortedset", "@fast"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zscan", -3, &["readonly"], 1, 1, 1, &["@read", "@sortedset", "@slow"], &["nondeterministic_output"], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zscore", 3, &["readonly", "fast"], 1, 1, 1, &["@read", "@sortedset", "@fast"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::Range(0, 1, 0))], &[]),
c("zunion", -3, &["readonly", "movablekeys"], 0, 0, 0, &["@read", "@sortedset", "@slow"], &[], &[k("", &["RO", "access"], Begin::Index(1), Find::KeyNum(0, 1, 1))], &[]),
c("zunionstore", -4, &["write", "denyoom", "movablekeys"], 1, 1, 1, &["@write", "@sortedset", "@slow"], &[], &[k("", &["OW", "update"], Begin::Index(1), Find::Range(0, 1, 0)), k("", &["RO", "access"], Begin::Index(2), Find::KeyNum(0, 1, 1))], &[]),
];
