#!/usr/bin/env bash
# Generate github.com/goliajp/kevy-go from bindings/go, and prove the
# result works standing alone.
#
#   bash scripts/mirror-go-module.sh              # generate + verify
#   bash scripts/mirror-go-module.sh --push 5.1.0 # ... then push + tag
#
# WHY A MIRROR AT ALL
#
# Go has no package registry. An import path IS a repository URL, so
# `import "github.com/goliajp/kevy-go/v5"` requires a repository at
# exactly that address with go.mod at its root — bindings/go inside the
# kevy tree cannot be imported by anyone. Every other binding publishes
# by uploading a built artifact; this one publishes by having a second
# repository exist.
#
# That repository is GENERATED, never edited. A hand-maintained copy of
# thirty source files is two copies of the same library, and they drift
# the first time a fix lands in the one someone happened to have open.
# So this script is the only thing that writes it, kevy is the only
# place changes are made, and the gate below fails the build if the two
# diverge.
#
# WHAT GOES IN IT
#
# The pure-Go half only: everything except the files carrying the
# `kevy_embedded` build tag. Those are cgo against the engine's static
# library, which is per-platform and tens of megabytes; a Go module
# ships SOURCE through the module proxy, so the library cannot travel
# with it in any case. Users who want the embedded engine build it from
# the kevy tree, where cargo has just produced the library — which is
# what errNoEmbedded tells them.
#
# The upshot for a consumer is the good outcome anyway: `go get` gives a
# working RESP client with no cgo, no toolchain, and no per-platform
# matrix, on every platform Go supports.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
SRC="$ROOT/bindings/go"
MODULE="github.com/goliajp/kevy-go/v5"
REPO="git@github.com:goliajp/kevy-go.git"

PUSH_VERSION=""
if [ "${1:-}" = "--push" ]; then
    PUSH_VERSION="${2:-}"
    [ -n "$PUSH_VERSION" ] || { echo "✗ --push needs a version, e.g. --push 5.1.0" >&2; exit 2; }
fi

# Built outside the kevy tree on purpose. Under it, the tagged files'
# `${SRCDIR}/../../crates/...` paths would still resolve, and a mirror
# that only works while sitting inside the repo it was extracted from
# would pass this check and fail for the first real user.
STAGE="$(mktemp -d "${TMPDIR:-/tmp}/kevy-go-mirror.XXXXXX")"
trap 'rm -rf "$STAGE"' EXIT
OUT="$STAGE/kevy-go"
mkdir -p "$OUT"

echo "→ selecting sources"
kept=0 skipped=0
for f in "$SRC"/*.go; do
    if head -1 "$f" | grep -q '^//go:build kevy_embedded'; then
        skipped=$((skipped + 1)); continue
    fi
    cp "$f" "$OUT/"; kept=$((kept + 1))
done
echo "  $kept files, $skipped left behind (embedded)"

# A stray `import "C"` outside the tagged set would make the mirror need
# a C toolchain — the one property this split exists to guarantee.
if grep -l '^import "C"' "$OUT"/*.go 2>/dev/null; then
    echo "✗ cgo in an untagged file: the mirror would not build without a C toolchain" >&2
    exit 1
fi

cp "$SRC/go.mod" "$OUT/"
cp "$ROOT/LICENSE-APACHE" "$ROOT/LICENSE-MIT" "$OUT/" 2>/dev/null || true

# The README a user meets at github.com/goliajp/kevy-go: it must open by
# saying this is generated, or the first drive-by fix arrives as a PR
# against a file that gets overwritten by the next release.
{
    printf '<!-- Generated by scripts/mirror-go-module.sh in goliajp/kevy. -->\n'
    printf '<!-- Do not edit here: edit bindings/go there. -->\n\n'
    printf '# kevy-go\n\n'
    printf 'The Go client for [kevy](https://github.com/goliajp/kevy) — a pure-Rust,\n'
    printf 'zero-dependency Redis-compatible engine.\n\n'
    printf 'This repository is **generated** from `bindings/go` in the kevy repo and\n'
    printf 'pushed on each release. It exists because a Go import path is a repository\n'
    printf 'URL, so the client has to live at the address people import. Issues and\n'
    printf 'pull requests belong on [goliajp/kevy](https://github.com/goliajp/kevy);\n'
    printf 'anything committed here is overwritten by the next release.\n\n'
    printf '```\ngo get %s\n```\n\n' "$MODULE"
    printf 'No cgo, no dependencies beyond the standard library.\n\n'
    printf '```go\nimport kevy "%s"\n\n' "$MODULE"
    printf 'c, err := kevy.Connect("kevy://127.0.0.1:6379")\n```\n\n'
    printf '## The embedded engine\n\n'
    printf 'kevy also runs in-process, addressed as `mem://` or `file://`. That backend\n'
    printf 'is cgo linked against the engine'"'"'s static library, which is per-platform\n'
    printf 'and far too large to travel through the Go module proxy — a Go module ships\n'
    printf 'source. So it is not in this repository. Build it from the kevy tree, where\n'
    printf 'cargo has just produced the library:\n\n'
    printf '```\ngit clone https://github.com/goliajp/kevy\ncd kevy && cargo build --release -p kevy-ffi\ncd bindings/go && go test -tags kevy_embedded ./...\n```\n\n'
    printf 'Without that tag, `mem://` and `file://` return an error saying so.\n\n'
    printf '## Documentation\n\nhttps://kevy.golia.jp\n'
} > "$OUT/README.md"

echo "→ verifying it stands alone"
cd "$OUT"
go build ./... || { echo "✗ the generated module does not build" >&2; exit 1; }
go vet ./... || { echo "✗ go vet on the generated module" >&2; exit 1; }

# Not just compiled: RUN. The server binary is passed in, since there is
# no kevy tree above the mirror to find one in. Without it the remote
# tests skip, and a green run would mean "nothing was checked" — so a
# missing binary is a failure here, not a skip.
BIN="${KEVY_SERVER_BIN:-$ROOT/target/release/kevy}"
if [ ! -x "$BIN" ]; then
    echo "✗ no server binary at $BIN" >&2
    echo "  Build it (cargo build --release -p kevy) or set KEVY_SERVER_BIN." >&2
    echo "  Skipping would leave every remote test skipped and the run green," >&2
    echo "  which is the same output as a working mirror." >&2
    exit 1
fi
KEVY_SERVER_BIN="$BIN" go test -v ./... > "$STAGE/test.log" 2>&1 || {
    echo "✗ the generated module fails its own tests" >&2
    grep -E '^(---|\s+\S+\.go:[0-9]+:)' "$STAGE/test.log" | head -30 >&2
    exit 1; }
# A suite that skipped everything also exits 0. The embedded tests SHOULD
# skip here — there is no engine in this build — so the check is that
# something ran, not that nothing skipped.
passed=$(grep -c '^--- PASS' "$STAGE/test.log" || true)
[ "$passed" -gt 0 ] || {
    echo "✗ every test skipped: green, and nothing was checked" >&2; exit 1; }
cd "$ROOT"
echo "  builds, vets, and passes $passed tests standing alone"

if [ -z "$PUSH_VERSION" ]; then
    # Gate mode: compare against what is published, so a change to
    # bindings/go that was never mirrored is caught at PR time rather
    # than discovered by a user on a stale module.
    echo "→ comparing against the published module"
    CLONE="$STAGE/published"
    if git clone --quiet --depth 1 "$REPO" "$CLONE" 2>/dev/null; then
        # .git aside, the two trees must be byte-identical.
        if diff -r -x '.git' "$CLONE" "$OUT" > "$STAGE/drift.txt" 2>&1; then
            echo "  ✓ in sync"
        else
            echo "  ! kevy-go is behind bindings/go:"
            sed 's/^/    /' "$STAGE/drift.txt" | head -40
            echo "    This is expected between releases — the release pushes it."
        fi
    else
        echo "  (cannot reach $REPO; generation was still verified)"
    fi
    exit 0
fi

echo "→ pushing $MODULE v$PUSH_VERSION"
# The tag must match the version the rest of the release ships, and Go's
# semantic import versioning requires the module path to carry /vN for
# major >= 2. A mismatch between the two is not a build error — it is a
# module that resolves to the wrong major forever.
MAJOR="${PUSH_VERSION%%.*}"
case "$MODULE" in
    */v"$MAJOR") ;;
    *) echo "✗ module path is $MODULE but the version is $PUSH_VERSION." >&2
       echo "  Go requires /v$MAJOR in the path for major >= 2. Update both." >&2
       exit 1;;
esac

WORK="$STAGE/push"
git clone --quiet "$REPO" "$WORK"
if git -C "$WORK" rev-parse "v$PUSH_VERSION" >/dev/null 2>&1; then
    echo "✗ v$PUSH_VERSION is already tagged on kevy-go." >&2
    echo "  A Go module version is immutable once the proxy has fetched it:" >&2
    echo "  moving the tag does not change what anyone downloads. Ship the" >&2
    echo "  next patch version instead." >&2
    exit 1
fi
find "$WORK" -mindepth 1 -maxdepth 1 ! -name .git -exec rm -rf {} +
cp -R "$OUT"/. "$WORK"/
git -C "$WORK" add -A
if git -C "$WORK" diff --cached --quiet; then
    echo "  content already current; tagging only"
else
    git -C "$WORK" commit --quiet -m "kevy $PUSH_VERSION

Generated from goliajp/kevy bindings/go by scripts/mirror-go-module.sh.
Do not edit here."
fi
git -C "$WORK" tag "v$PUSH_VERSION"
# ONE atomic push, not a branch push followed by a tag push. Between
# two pushes there is a window where the repository has the commit and
# not the tag, and anything that fetches during it — the module proxy,
# the checksum database — records "unknown revision" and caches that
# answer for far longer than the window lasted. --atomic makes the ref
# update all-or-nothing on the server.
git -C "$WORK" push --quiet --atomic origin HEAD:main "v$PUSH_VERSION"
echo "  ✓ pushed and tagged v$PUSH_VERSION"

cat <<NOTE

Verify by fetching, not by trusting the push — the module proxy is what
users resolve through, and it caches independently of the repository:

    GOPROXY=proxy.golang.org go install $MODULE@v$PUSH_VERSION 2>&1 | head -3
    curl -sf https://proxy.golang.org/${MODULE}/@v/v$PUSH_VERSION.info

The proxy fetches on first request, so the first call may take a moment.
NOTE
