#!/usr/bin/env python3
"""Build the site's llms.txt and llms-full.txt.

The repository's llms.txt is generated by `cargo run -p kevy --bin gen_docs`
from the engine's verb table, and its links are relative paths into docs/ — the
right thing for someone reading the repo. Served from kevy.golia.jp those links
are dead, so the site gets its own copy with absolute URLs.

llms-full.txt is the whole thing inlined: the verb table plus every
document, in one file. An assistant that can fetch exactly one URL should be
able to fetch that one and know how to use kevy correctly — including the parts
where kevy does NOT behave the way Redis's documentation says, which is the
whole reason a generic "it's Redis-compatible" answer gets people into trouble.

Run: python3 tools/gen_llms.py [--check]
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SITE = "https://kevy.golia.jp"
# `main` is a branch this repository does not have; every link built
# from it 404s. Keep it next to the site generator's REPO_REF.
GH = "https://github.com/goliajp/kevy/blob/develop"

# Reading order. The first three are the ones an assistant needs before it
# writes a single command; the rest answer questions as they come up.
ORDER = [
    "designing-on-kevy", "cookbook", "rds-workloads",
    "persistence", "tuning", "error-replies",
    "indexes", "tables", "vector-search", "text-search", "views", "cdc", "pubsub", "lua",
    "replication", "availability", "cluster", "tiering", "accept-shards", "uds", "async",
    "wasm", "embedded-listener", "iot",
    "migration", "UPGRADING",
]


def site_links(txt):
    """docs/foo.md -> https://kevy.golia.jp/docs/foo/ ; the generated
    verb-reference has no page of its own, so it points at the command index."""

    def sub(m):
        name = m.group(1)
        if name == "verb-reference":
            return f"]({SITE}/docs/commands/)"
        return f"]({SITE}/docs/{name}/)"

    return re.sub(r"\]\(docs/([\w.-]+)\.md\)", sub, txt)


def main():
    check = "--check" in sys.argv
    base = (ROOT / "llms.txt").read_text(encoding="utf-8")

    # ── llms.txt for the site ──
    lite = site_links(base)
    lite = lite.replace(
        "This file is\nGENERATED from the server's verb metadata table — do not edit by hand.",
        "This file is\nGENERATED from the server's verb metadata table — do not edit by hand.\n"
        f"The full text of every document below is inlined at {SITE}/llms-full.txt,\n"
        "which is one fetch and needs no crawling.",
    )

    # ── llms-full.txt ──
    docs = []
    for name in ORDER:
        p = ROOT / "docs" / f"{name}.md"
        if not p.exists():
            continue
        body = p.read_text(encoding="utf-8").strip()
        # Rewrite intra-doc links so a reader of the concatenation can still
        # follow them out to the web.
        body = re.sub(
            r"\]\((?:\.{1,2}/)*([\w.-]+)\.md((?:#[\w-]+)?)\)",
            lambda m: f"]({SITE}/docs/{m.group(1)}/{m.group(2)})",
            body,
        )
        body = re.sub(
            r"\]\((?:\.{1,2}/)+((?:bench|crates|tools)/[^)]+)\)",
            lambda m: f"]({GH}/{m.group(1)})",
            body,
        )
        docs.append(f"\n\n{'=' * 78}\n# {name}\n{'=' * 78}\n\n{body}")

    full = (
        lite.rstrip()
        + "\n\n\n"
        + "=" * 78
        + "\n# FULL DOCUMENTATION\n"
        + "=" * 78
        + "\n\nEverything below is the complete text of kevy's documentation, in the order\n"
        "an assistant should read it. The first three documents matter most: they are\n"
        "what stops you from writing Redis code that compiles here and then behaves\n"
        "differently.\n"
        + "".join(docs)
        + "\n"
    )

    want = {
        ROOT / "site/llms.txt": lite,
        ROOT / "site/llms-full.txt": full,
    }

    if check:
        stale = [p for p, t in want.items()
                 if not p.exists() or p.read_text(encoding="utf-8") != t]
        if stale:
            for p in stale:
                print(f"STALE {p.relative_to(ROOT)}")
            print("Regenerate with `python3 tools/gen_llms.py`.")
            return 1
        print("ok: site/llms.txt and site/llms-full.txt are current")
        return 0

    for p, t in want.items():
        p.write_text(t, encoding="utf-8")
        kb = len(t.encode()) / 1024
        print(f"  wrote {p.relative_to(ROOT)} ({kb:.0f} KB)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
